.TH "pyrst.pyrst.exceptions.SpaceIDException" 3 "Fri Feb 20 2015" "Version 0.50" "Pyrst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyrst.pyrst.exceptions.SpaceIDException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyrst from the source code\&.
