.TH "pyrst.pyrst.handlers.DfHandler" 3 "Fri Feb 20 2015" "Version 0.50" "Pyrst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyrst.pyrst.handlers.DfHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpyrst\&.pyrst\&.handlers\&.Handler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBprocess\fP (self, query_output)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler that returns a Pandas dataFrame

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyrst from the source code\&.
