.TH "pyrst.pyrst.helpers.Instance" 3 "Fri Feb 20 2015" "Version 0.50" "Pyrst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyrst.pyrst.helpers.Instance \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, colnames, rows)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcolnames\fP"
.br
.ti -1c
.RI "\fBrows\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyrst from the source code\&.
