.TH "pyrst.pyrst.handlers.Handler" 3 "Fri Feb 20 2015" "Version 0.50" "Pyrst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyrst.pyrst.handlers.Handler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpyrst\&.pyrst\&.handlers\&.DfHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBprocess\fP (self, query_output)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pyrst from the source code\&.
